/*
 * Writes data/version.js — the build stamp shown in the app header, so you can tell
 * at a glance whether the page you're playing includes your latest changes.
 *
 * Run by the pre-commit hook (see below); safe to run by hand any time:
 *   node scripts/stamp-version.mjs
 *
 * The commit SHA can't be known before the commit exists, so the stamp carries the
 * commit *time* plus a short hash of the app's own source files. The hash is the
 * precise answer to "is what I'm playing what I have locally" — it changes whenever
 * any tracked source file changes, and is stable when nothing did.
 */
import { createHash } from "crypto";
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const FILES = [
  "index.html", "sw.js", "manifest.webmanifest",
  "src/app.js", "src/draft.js", "src/rankings.js", "src/styles.css",
  "data/players.js", "data/league.js",
];

const h = createHash("sha1");
for (const f of FILES) {
  try { h.update(readFileSync(join(root, f))); } catch { /* file may not exist yet */ }
}

const stamp = { hash: h.digest("hex").slice(0, 7), at: new Date().toISOString() };
writeFileSync(
  join(root, "data/version.js"),
  `/* Generated by scripts/stamp-version.mjs — do not edit. */\n` +
  `window.BUILD = ${JSON.stringify(stamp)};\n`
);
console.log(`stamped ${stamp.hash} ${stamp.at}`);
